onboarding = false

[theme]
name = "tokyo-night"

[keys]
remove_worktree = "prefix+alt+d"
previous_workspace = "prefix+shift+left"
next_workspace = "prefix+shift+right"
switch_workspace = "prefix+shift+1..9"
previous_agent = "prefix+alt+p"
next_agent = "prefix+alt+n"
focus_agent = "prefix+alt+1..9"

[ui.sound]
enabled = true

[ui.toast]
delivery = "system"

[ui]
show_agent_labels_on_pane_borders = true
agent_panel_scope = "all"
prompt_new_tab_name = false

[worktrees]
directory = "/home/realgh/.worktrees"
